languageCode = 'en-us'
#title = 'nibble & nosh'
theme = 'summer-qremix'
[params]
  color= '#ffda03'
  font= 'Preahvihear'
  resources= []
  logo_image= 'logo.svg'
  favicon_image= 'favicon.png'
[markup]
  [goldmark]
    [renderer]
      unsafe= true
